"""add user - team relationship

Revision ID: 0495db78a34c
Revises: c819c3d4451a
Create Date: 2026-05-27 22:30:54.497892

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '0495db78a34c'
down_revision: Union[str, Sequence[str], None] = 'c819c3d4451a'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('user_consents',
    sa.Column('uuid', sa.UUID(as_uuid=False), nullable=False),
    sa.Column('user_uuid', sa.UUID(as_uuid=False), nullable=False),
    sa.Column('consent_type', sa.Enum('terms', 'privacy', 'third_party', 'marketing', name='consenttype'), nullable=False),
    sa.Column('version', sa.String(length=20), nullable=False),
    sa.Column('accepted_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('revoked_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('ip_address', sa.String(length=45), nullable=True),
    sa.ForeignKeyConstraint(['user_uuid'], ['users.uuid'], ),
    sa.PrimaryKeyConstraint('uuid')
    )
    op.create_index(op.f('ix_user_consents_user_uuid'), 'user_consents', ['user_uuid'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_user_consents_user_uuid'), table_name='user_consents')
    op.drop_table('user_consents')
    # ### end Alembic commands ###
