"""add user_profile seed + team model properties sprint add

Revision ID: 15598f052b75
Revises: e67a9eea35e9
Create Date: 2026-05-31 14:33:07.970709

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '15598f052b75'
down_revision: Union[str, Sequence[str], None] = 'e67a9eea35e9'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('teams', sa.Column('leader_name', sa.String(length=32), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('teams', 'leader_name')
    # ### end Alembic commands ###
