"""add hr onboaring, offboadring, one on one

Revision ID: 4510e2cf9370
Revises: 722ba390d28f
Create Date: 2026-06-26 23:19:26.133144

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = '4510e2cf9370'
down_revision: Union[str, Sequence[str], None] = '722ba390d28f'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('leave_requests',
    sa.Column('uuid', sa.UUID(as_uuid=False), nullable=False),
    sa.Column('workspace_uuid', sa.UUID(as_uuid=False), nullable=False),
    sa.Column('requester_member_uuid', sa.UUID(as_uuid=False), nullable=False),
    sa.Column('leave_type', sa.Enum('annual', 'sick', 'family', 'compensatory', 'public', 'parental', 'maternity', name='leave_type'), nullable=False),
    sa.Column('start_date', sa.Date(), nullable=False),
    sa.Column('end_date', sa.Date(), nullable=False),
    sa.Column('half_day', sa.Boolean(), server_default=sa.text('false'), nullable=False),
    sa.Column('reason_md', sa.Text(), nullable=True),
    sa.Column('attachments', postgresql.JSONB(astext_type=sa.Text()), server_default=sa.text("'[]'::jsonb"), nullable=False),
    sa.Column('status', sa.Enum('draft', 'submitted', 'approved', 'rejected', 'consumed', 'cancelled', name='leave_status'), nullable=False),
    sa.Column('approver_member_uuid', sa.UUID(as_uuid=False), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('deleted_at', sa.DateTime(timezone=True), nullable=True),
    sa.ForeignKeyConstraint(['approver_member_uuid'], ['members.uuid'], ),
    sa.ForeignKeyConstraint(['requester_member_uuid'], ['members.uuid'], ),
    sa.ForeignKeyConstraint(['workspace_uuid'], ['workspaces.uuid'], ),
    sa.PrimaryKeyConstraint('uuid')
    )
    op.create_index('idx_leave_requests_workspace_requester_status_dates', 'leave_requests', ['workspace_uuid', 'requester_member_uuid', 'status', 'start_date'], unique=False)
    op.create_table('offboarding_workflows',
    sa.Column('uuid', sa.UUID(as_uuid=False), nullable=False),
    sa.Column('workspace_uuid', sa.UUID(as_uuid=False), nullable=False),
    sa.Column('target_member_uuid', sa.UUID(as_uuid=False), nullable=False),
    sa.Column('reason_code', sa.Enum('resignation', 'agreed_termination', 'dismissal', 'contract_end', 'retirement', name='offboarding_reason_code'), nullable=False),
    sa.Column('requires_labor_review', sa.Boolean(), server_default=sa.text('false'), nullable=False),
    sa.Column('effective_date', sa.Date(), nullable=False),
    sa.Column('phase', sa.Enum('draft', 'pending_review', 'in_progress', 'completed', name='offboarding_phase'), nullable=False),
    sa.Column('final_payment_status', sa.Enum('pending', 'scheduled', 'paid', name='offboarding_final_payment_status'), nullable=True),
    sa.Column('data_retention_policy', sa.String(length=64), server_default=sa.text("'default'"), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('deleted_at', sa.DateTime(timezone=True), nullable=True),
    sa.ForeignKeyConstraint(['target_member_uuid'], ['members.uuid'], ),
    sa.ForeignKeyConstraint(['workspace_uuid'], ['workspaces.uuid'], ),
    sa.PrimaryKeyConstraint('uuid')
    )
    op.create_index('idx_offboarding_workflows_requires_labor_review', 'offboarding_workflows', ['workspace_uuid'], unique=False, postgresql_where=sa.text('requires_labor_review = true'))
    op.create_index('idx_offboarding_workflows_workspace_target', 'offboarding_workflows', ['workspace_uuid', 'target_member_uuid'], unique=False)
    op.create_table('onboarding_workflows',
    sa.Column('uuid', sa.UUID(as_uuid=False), nullable=False),
    sa.Column('workspace_uuid', sa.UUID(as_uuid=False), nullable=False),
    sa.Column('target_member_uuid', sa.UUID(as_uuid=False), nullable=False),
    sa.Column('template_uuid', sa.UUID(as_uuid=False), nullable=True),
    sa.Column('phase', sa.Enum('pending', 'in_progress', 'completed', 'cancelled', name='onboarding_phase'), nullable=False),
    sa.Column('started_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('completed_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('progress_pct', sa.Integer(), server_default=sa.text('0'), nullable=False),
    sa.Column('assigned_buddy_member_uuid', sa.UUID(as_uuid=False), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('deleted_at', sa.DateTime(timezone=True), nullable=True),
    sa.ForeignKeyConstraint(['assigned_buddy_member_uuid'], ['members.uuid'], ),
    sa.ForeignKeyConstraint(['target_member_uuid'], ['members.uuid'], ),
    sa.ForeignKeyConstraint(['workspace_uuid'], ['workspaces.uuid'], ),
    sa.PrimaryKeyConstraint('uuid')
    )
    op.create_index('idx_onboarding_workflows_workspace_phase', 'onboarding_workflows', ['workspace_uuid', 'phase'], unique=False)
    op.create_index('idx_onboarding_workflows_workspace_target', 'onboarding_workflows', ['workspace_uuid', 'target_member_uuid'], unique=False)
    op.create_table('one_on_ones',
    sa.Column('uuid', sa.UUID(as_uuid=False), nullable=False),
    sa.Column('workspace_uuid', sa.UUID(as_uuid=False), nullable=False),
    sa.Column('manager_member_uuid', sa.UUID(as_uuid=False), nullable=False),
    sa.Column('report_member_uuid', sa.UUID(as_uuid=False), nullable=False),
    sa.Column('scheduled_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('held_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('notes_md', sa.Text(), nullable=True),
    sa.Column('action_items', postgresql.JSONB(astext_type=sa.Text()), server_default=sa.text("'[]'::jsonb"), nullable=False),
    sa.Column('mood', sa.String(length=32), nullable=True),
    sa.Column('visibility', sa.Enum('manager_and_report', 'report_only_after_session', name='one_on_one_visibility'), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['manager_member_uuid'], ['members.uuid'], ),
    sa.ForeignKeyConstraint(['report_member_uuid'], ['members.uuid'], ),
    sa.ForeignKeyConstraint(['workspace_uuid'], ['workspaces.uuid'], ),
    sa.PrimaryKeyConstraint('uuid')
    )
    op.create_index('idx_one_on_ones_workspace_manager_report_scheduled', 'one_on_ones', ['workspace_uuid', 'manager_member_uuid', 'report_member_uuid', 'scheduled_at'], unique=False)
    op.create_table('onboarding_steps',
    sa.Column('uuid', sa.UUID(as_uuid=False), nullable=False),
    sa.Column('workflow_uuid', sa.UUID(as_uuid=False), nullable=False),
    sa.Column('workspace_uuid', sa.UUID(as_uuid=False), nullable=False),
    sa.Column('kind', sa.Enum('account_provision', 'channel_join', 'equipment', 'document_sign', 'training', 'kpi_setup', name='onboarding_step_kind'), nullable=False),
    sa.Column('target_domain', sa.Enum('pm', 'comms', 'documents', name='onboarding_target_domain'), nullable=True),
    sa.Column('target_payload', postgresql.JSONB(astext_type=sa.Text()), server_default=sa.text("'{}'::jsonb"), nullable=False),
    sa.Column('status', sa.Enum('pending', 'in_progress', 'done', 'skipped', name='onboarding_step_status'), nullable=False),
    sa.Column('due_date', sa.Date(), nullable=True),
    sa.Column('responsible_member_uuid', sa.UUID(as_uuid=False), nullable=True),
    sa.Column('step_order', sa.Integer(), server_default=sa.text('0'), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['responsible_member_uuid'], ['members.uuid'], ),
    sa.ForeignKeyConstraint(['workflow_uuid'], ['onboarding_workflows.uuid'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['workspace_uuid'], ['workspaces.uuid'], ),
    sa.PrimaryKeyConstraint('uuid')
    )
    op.create_index('idx_onboarding_steps_workflow_order', 'onboarding_steps', ['workflow_uuid', 'step_order'], unique=False)
    op.create_index('idx_onboarding_steps_workspace_status', 'onboarding_steps', ['workspace_uuid', 'status'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index('idx_onboarding_steps_workspace_status', table_name='onboarding_steps')
    op.drop_index('idx_onboarding_steps_workflow_order', table_name='onboarding_steps')
    op.drop_table('onboarding_steps')
    op.drop_index('idx_one_on_ones_workspace_manager_report_scheduled', table_name='one_on_ones')
    op.drop_table('one_on_ones')
    op.drop_index('idx_onboarding_workflows_workspace_target', table_name='onboarding_workflows')
    op.drop_index('idx_onboarding_workflows_workspace_phase', table_name='onboarding_workflows')
    op.drop_table('onboarding_workflows')
    op.drop_index('idx_offboarding_workflows_workspace_target', table_name='offboarding_workflows')
    op.drop_index('idx_offboarding_workflows_requires_labor_review', table_name='offboarding_workflows', postgresql_where=sa.text('requires_labor_review = true'))
    op.drop_table('offboarding_workflows')
    op.drop_index('idx_leave_requests_workspace_requester_status_dates', table_name='leave_requests')
    op.drop_table('leave_requests')
    # ### end Alembic commands ###
