"""add comms

Revision ID: 4aace4e5c53e
Revises: fdf5f2845854
Create Date: 2026-06-26 22:39:58.890277

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = '4aace4e5c53e'
down_revision: Union[str, Sequence[str], None] = 'fdf5f2845854'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('channels',
    sa.Column('uuid', sa.UUID(as_uuid=False), nullable=False),
    sa.Column('workspace_uuid', sa.UUID(as_uuid=False), nullable=False),
    sa.Column('name', sa.String(length=100), nullable=False),
    sa.Column('type', sa.Enum('public', 'private', 'dm', 'external', name='channel_type'), nullable=False),
    sa.Column('topic', sa.Text(), nullable=True),
    sa.Column('is_archived', sa.Boolean(), server_default=sa.text('false'), nullable=False),
    sa.Column('created_by_member_uuid', sa.UUID(as_uuid=False), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('deleted_at', sa.DateTime(timezone=True), nullable=True),
    sa.ForeignKeyConstraint(['created_by_member_uuid'], ['members.uuid'], ),
    sa.ForeignKeyConstraint(['workspace_uuid'], ['workspaces.uuid'], ),
    sa.PrimaryKeyConstraint('uuid')
    )
    op.create_index('idx_channels_created_by', 'channels', ['created_by_member_uuid'], unique=False)
    op.create_index('idx_channels_workspace_type', 'channels', ['workspace_uuid', 'type'], unique=False)
    op.create_index('uq_channels_workspace_name', 'channels', ['workspace_uuid', 'name'], unique=True, postgresql_where=sa.text("type IN ('public', 'private')"))
    op.create_table('channel_members',
    sa.Column('channel_uuid', sa.UUID(as_uuid=False), nullable=False),
    sa.Column('member_uuid', sa.UUID(as_uuid=False), nullable=False),
    sa.Column('workspace_uuid', sa.UUID(as_uuid=False), nullable=False),
    sa.Column('joined_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('left_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('last_read_message_uuid', sa.UUID(as_uuid=False), nullable=True),
    sa.ForeignKeyConstraint(['channel_uuid'], ['channels.uuid'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['member_uuid'], ['members.uuid'], ),
    sa.ForeignKeyConstraint(['workspace_uuid'], ['workspaces.uuid'], ),
    sa.PrimaryKeyConstraint('channel_uuid', 'member_uuid')
    )
    op.create_index('idx_channel_members_workspace_channel_active', 'channel_members', ['workspace_uuid', 'channel_uuid'], unique=False, postgresql_where=sa.text('left_at IS NULL'))
    op.create_index('idx_channel_members_workspace_member', 'channel_members', ['workspace_uuid', 'member_uuid'], unique=False)
    op.create_table('messages',
    sa.Column('uuid', sa.UUID(as_uuid=False), nullable=False),
    sa.Column('workspace_uuid', sa.UUID(as_uuid=False), nullable=False),
    sa.Column('channel_uuid', sa.UUID(as_uuid=False), nullable=False),
    sa.Column('thread_root_uuid', sa.UUID(as_uuid=False), nullable=True),
    sa.Column('author_member_uuid', sa.UUID(as_uuid=False), nullable=False),
    sa.Column('body', sa.Text(), nullable=False),
    sa.Column('attachments', postgresql.JSONB(astext_type=sa.Text()), server_default=sa.text("'[]'::jsonb"), nullable=False),
    sa.Column('mentions', postgresql.ARRAY(sa.UUID(as_uuid=False)), server_default=sa.text("'{}'::uuid[]"), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('edited_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('deleted_at', sa.DateTime(timezone=True), nullable=True),
    sa.ForeignKeyConstraint(['author_member_uuid'], ['members.uuid'], ),
    sa.ForeignKeyConstraint(['channel_uuid'], ['channels.uuid'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['thread_root_uuid'], ['messages.uuid'], ),
    sa.ForeignKeyConstraint(['workspace_uuid'], ['workspaces.uuid'], ),
    sa.PrimaryKeyConstraint('uuid')
    )
    op.create_index('idx_messages_mentions', 'messages', ['mentions'], unique=False, postgresql_using='gin')
    op.create_index('idx_messages_workspace_author_created', 'messages', ['workspace_uuid', 'author_member_uuid', 'created_at'], unique=False)
    op.create_index('idx_messages_workspace_channel_created', 'messages', ['workspace_uuid', 'channel_uuid', 'created_at'], unique=False)
    op.create_index('idx_messages_workspace_thread', 'messages', ['workspace_uuid', 'thread_root_uuid', 'created_at'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index('idx_messages_workspace_thread', table_name='messages')
    op.drop_index('idx_messages_workspace_channel_created', table_name='messages')
    op.drop_index('idx_messages_workspace_author_created', table_name='messages')
    op.drop_index('idx_messages_mentions', table_name='messages', postgresql_using='gin')
    op.drop_table('messages')
    op.drop_index('idx_channel_members_workspace_member', table_name='channel_members')
    op.drop_index('idx_channel_members_workspace_channel_active', table_name='channel_members', postgresql_where=sa.text('left_at IS NULL'))
    op.drop_table('channel_members')
    op.drop_index('uq_channels_workspace_name', table_name='channels', postgresql_where=sa.text("type IN ('public', 'private')"))
    op.drop_index('idx_channels_workspace_type', table_name='channels')
    op.drop_index('idx_channels_created_by', table_name='channels')
    op.drop_table('channels')
    # ### end Alembic commands ###
