"""add hr: employee_profiles, org_units

Revision ID: 722ba390d28f
Revises: b02b03e8702c
Create Date: 2026-06-26 23:12:09.145982

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '722ba390d28f'
down_revision: Union[str, Sequence[str], None] = 'b02b03e8702c'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('org_units',
    sa.Column('uuid', sa.UUID(as_uuid=False), nullable=False),
    sa.Column('workspace_uuid', sa.UUID(as_uuid=False), nullable=False),
    sa.Column('parent_org_unit_uuid', sa.UUID(as_uuid=False), nullable=True),
    sa.Column('name', sa.String(length=100), nullable=False),
    sa.Column('manager_member_uuid', sa.UUID(as_uuid=False), nullable=True),
    sa.Column('kind', sa.Enum('department', 'team', 'squad', name='org_unit_kind'), nullable=False),
    sa.Column('cost_center_code', sa.String(length=32), nullable=True),
    sa.Column('is_archived', sa.Boolean(), server_default=sa.text('false'), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('deleted_at', sa.DateTime(timezone=True), nullable=True),
    sa.ForeignKeyConstraint(['manager_member_uuid'], ['members.uuid'], ),
    sa.ForeignKeyConstraint(['parent_org_unit_uuid'], ['org_units.uuid'], ),
    sa.ForeignKeyConstraint(['workspace_uuid'], ['workspaces.uuid'], ),
    sa.PrimaryKeyConstraint('uuid')
    )
    op.create_index('idx_org_units_workspace_manager', 'org_units', ['workspace_uuid', 'manager_member_uuid'], unique=False)
    op.create_index('idx_org_units_workspace_parent', 'org_units', ['workspace_uuid', 'parent_org_unit_uuid'], unique=False)
    op.create_table('employee_profiles',
    sa.Column('uuid', sa.UUID(as_uuid=False), nullable=False),
    sa.Column('workspace_uuid', sa.UUID(as_uuid=False), nullable=False),
    sa.Column('member_uuid', sa.UUID(as_uuid=False), nullable=False),
    sa.Column('employee_no', sa.String(length=32), nullable=True),
    sa.Column('title', sa.String(length=100), nullable=True),
    sa.Column('org_unit_uuid', sa.UUID(as_uuid=False), nullable=True),
    sa.Column('employment_type', sa.Enum('regular', 'contract', 'outsourced', 'intern', name='employment_type'), nullable=False),
    sa.Column('hired_at', sa.Date(), nullable=True),
    sa.Column('manager_member_uuid', sa.UUID(as_uuid=False), nullable=True),
    sa.Column('birth_date', sa.Date(), nullable=True),
    sa.Column('phone', sa.String(length=32), nullable=True),
    sa.Column('tenure_status', sa.Enum('candidate', 'pre_hire', 'active', 'on_leave', 'pre_offboarding', 'offboarded', 'archived_legal', name='tenure_status'), nullable=False),
    sa.Column('leave_balance_days', sa.Numeric(precision=5, scale=2), nullable=True),
    sa.Column('insurance_consent_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('contract_signed_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('data_retention_expires_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('deleted_at', sa.DateTime(timezone=True), nullable=True),
    sa.ForeignKeyConstraint(['manager_member_uuid'], ['members.uuid'], ),
    sa.ForeignKeyConstraint(['member_uuid'], ['members.uuid'], ),
    sa.ForeignKeyConstraint(['org_unit_uuid'], ['org_units.uuid'], ),
    sa.ForeignKeyConstraint(['workspace_uuid'], ['workspaces.uuid'], ),
    sa.PrimaryKeyConstraint('uuid'),
    sa.UniqueConstraint('workspace_uuid', 'member_uuid', name='uq_employee_profiles_workspace_member')
    )
    op.create_index('idx_employee_profiles_workspace_manager', 'employee_profiles', ['workspace_uuid', 'manager_member_uuid'], unique=False)
    op.create_index('idx_employee_profiles_workspace_org_unit', 'employee_profiles', ['workspace_uuid', 'org_unit_uuid'], unique=False)
    op.create_index('idx_employee_profiles_workspace_tenure', 'employee_profiles', ['workspace_uuid', 'tenure_status'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index('idx_employee_profiles_workspace_tenure', table_name='employee_profiles')
    op.drop_index('idx_employee_profiles_workspace_org_unit', table_name='employee_profiles')
    op.drop_index('idx_employee_profiles_workspace_manager', table_name='employee_profiles')
    op.drop_table('employee_profiles')
    op.drop_index('idx_org_units_workspace_parent', table_name='org_units')
    op.drop_index('idx_org_units_workspace_manager', table_name='org_units')
    op.drop_table('org_units')
    # ### end Alembic commands ###
