"""add event_outbox + audit_domain.system

Revision ID: b02b03e8702c
Revises: 36bcc89841da
Create Date: 2026-06-26 22:57:10.232606

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = 'b02b03e8702c'
down_revision: Union[str, Sequence[str], None] = '36bcc89841da'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('event_outbox',
    sa.Column('uuid', sa.UUID(as_uuid=False), nullable=False),
    sa.Column('workspace_uuid', sa.UUID(as_uuid=False), nullable=False),
    sa.Column('event_name', sa.String(length=80), nullable=False),
    sa.Column('payload', postgresql.JSONB(astext_type=sa.Text()), server_default=sa.text("'{}'::jsonb"), nullable=False),
    sa.Column('occurred_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('published_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('trace_id', sa.String(length=64), nullable=True),
    sa.ForeignKeyConstraint(['workspace_uuid'], ['workspaces.uuid'], ),
    sa.PrimaryKeyConstraint('uuid')
    )
    op.create_index('idx_event_outbox_unpublished', 'event_outbox', ['occurred_at'], unique=False, postgresql_where=sa.text('published_at IS NULL'))
    op.create_index('idx_event_outbox_workspace_event_occurred', 'event_outbox', ['workspace_uuid', 'event_name', 'occurred_at'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index('idx_event_outbox_workspace_event_occurred', table_name='event_outbox')
    op.drop_index('idx_event_outbox_unpublished', table_name='event_outbox', postgresql_where=sa.text('published_at IS NULL'))
    op.drop_table('event_outbox')
    # ### end Alembic commands ###
