"""add workspace

Revision ID: bce8e5e54b17
Revises: a1b2c3d4e5f6
Create Date: 2026-06-26 22:18:47.421806

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = 'bce8e5e54b17'
down_revision: Union[str, Sequence[str], None] = 'a1b2c3d4e5f6'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('workspaces',
    sa.Column('uuid', sa.UUID(as_uuid=False), nullable=False),
    sa.Column('name', sa.String(length=100), nullable=False),
    sa.Column('slug', sa.String(length=64), nullable=False),
    sa.Column('tier', sa.Enum('free', 'team', 'business', 'enterprise', name='workspace_tier'), nullable=False),
    sa.Column('region', sa.Enum('kr', 'jp', name='workspace_region'), nullable=False),
    sa.Column('billing_account_uuid', sa.UUID(as_uuid=False), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('deleted_at', sa.DateTime(timezone=True), nullable=True),
    sa.PrimaryKeyConstraint('uuid'),
    sa.UniqueConstraint('slug')
    )
    op.create_index('idx_workspaces_slug', 'workspaces', ['slug'], unique=False)
    op.create_index('idx_workspaces_tier', 'workspaces', ['tier'], unique=False)
    op.create_table('members',
    sa.Column('uuid', sa.UUID(as_uuid=False), nullable=False),
    sa.Column('workspace_uuid', sa.UUID(as_uuid=False), nullable=False),
    sa.Column('user_uuid', sa.UUID(as_uuid=False), nullable=True),
    sa.Column('display_name', sa.String(length=64), nullable=False),
    sa.Column('email', sa.String(length=100), nullable=False),
    sa.Column('status', sa.Enum('invited', 'active', 'disabled', 'external', name='member_status'), nullable=False),
    sa.Column('joined_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('deleted_at', sa.DateTime(timezone=True), nullable=True),
    sa.ForeignKeyConstraint(['user_uuid'], ['users.uuid'], ),
    sa.ForeignKeyConstraint(['workspace_uuid'], ['workspaces.uuid'], ),
    sa.PrimaryKeyConstraint('uuid'),
    sa.UniqueConstraint('workspace_uuid', 'email', name='uq_members_workspace_email'),
    sa.UniqueConstraint('workspace_uuid', 'user_uuid', name='uq_members_workspace_user')
    )
    op.create_index('idx_members_user', 'members', ['user_uuid'], unique=False)
    op.create_index('idx_members_workspace_email', 'members', ['workspace_uuid', 'email'], unique=False)
    op.create_index('idx_members_workspace_status', 'members', ['workspace_uuid', 'status'], unique=False)
    op.drop_index(op.f('ix_survey_responses_respondent_role'), table_name='survey_responses')
    op.drop_index(op.f('ix_survey_responses_survey_key'), table_name='survey_responses')
    op.drop_table('survey_responses')
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('survey_responses',
    sa.Column('uuid', sa.UUID(), autoincrement=False, nullable=False),
    sa.Column('created_at', postgresql.TIMESTAMP(timezone=True), autoincrement=False, nullable=False),
    sa.Column('survey_key', sa.VARCHAR(length=64), autoincrement=False, nullable=False),
    sa.Column('respondent_role', sa.VARCHAR(length=50), autoincrement=False, nullable=False),
    sa.Column('organization', sa.VARCHAR(length=200), autoincrement=False, nullable=True),
    sa.Column('contact_email', sa.VARCHAR(length=200), autoincrement=False, nullable=True),
    sa.Column('consents_to_followup', sa.BOOLEAN(), autoincrement=False, nullable=False),
    sa.Column('answers', postgresql.JSONB(astext_type=sa.Text()), autoincrement=False, nullable=False),
    sa.Column('ip_address', sa.VARCHAR(length=45), autoincrement=False, nullable=True),
    sa.Column('user_agent', sa.VARCHAR(length=512), autoincrement=False, nullable=True),
    sa.PrimaryKeyConstraint('uuid', name=op.f('survey_responses_pkey'))
    )
    op.create_index(op.f('ix_survey_responses_survey_key'), 'survey_responses', ['survey_key'], unique=False)
    op.create_index(op.f('ix_survey_responses_respondent_role'), 'survey_responses', ['respondent_role'], unique=False)
    op.drop_index('idx_members_workspace_status', table_name='members')
    op.drop_index('idx_members_workspace_email', table_name='members')
    op.drop_index('idx_members_user', table_name='members')
    op.drop_table('members')
    op.drop_index('idx_workspaces_tier', table_name='workspaces')
    op.drop_index('idx_workspaces_slug', table_name='workspaces')
    op.drop_table('workspaces')
    # ### end Alembic commands ###
