"""add hr extra entities documents hr events

Revision ID: c299af648922
Revises: 4510e2cf9370
Create Date: 2026-06-26 23:46:57.274388

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = 'c299af648922'
down_revision: Union[str, Sequence[str], None] = '4510e2cf9370'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('retention_policies',
    sa.Column('uuid', sa.UUID(as_uuid=False), nullable=False),
    sa.Column('workspace_uuid', sa.UUID(as_uuid=False), nullable=False),
    sa.Column('name', sa.String(length=100), nullable=False),
    sa.Column('retention_days', sa.Integer(), nullable=True),
    sa.Column('immutable', sa.Boolean(), server_default=sa.text('false'), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('deleted_at', sa.DateTime(timezone=True), nullable=True),
    sa.ForeignKeyConstraint(['workspace_uuid'], ['workspaces.uuid'], ),
    sa.PrimaryKeyConstraint('uuid')
    )
    op.create_index('idx_retention_policies_workspace', 'retention_policies', ['workspace_uuid'], unique=False)
    op.create_table('document_templates',
    sa.Column('uuid', sa.UUID(as_uuid=False), nullable=False),
    sa.Column('workspace_uuid', sa.UUID(as_uuid=False), nullable=False),
    sa.Column('name', sa.String(length=150), nullable=False),
    sa.Column('category', sa.Enum('labor', 'tax', 'internal_issuance', 'external_submission', 'report', name='document_category'), nullable=False),
    sa.Column('subtype', sa.String(length=64), nullable=False),
    sa.Column('body_md', sa.Text(), nullable=False),
    sa.Column('variables_schema', postgresql.JSONB(astext_type=sa.Text()), server_default=sa.text("'[]'::jsonb"), nullable=False),
    sa.Column('default_review_workflow_uuid', sa.UUID(as_uuid=False), nullable=True),
    sa.Column('default_retention_policy_uuid', sa.UUID(as_uuid=False), nullable=False),
    sa.Column('requires_signature', sa.Boolean(), server_default=sa.text('false'), nullable=False),
    sa.Column('version', sa.String(length=32), nullable=False),
    sa.Column('state', sa.Enum('draft', 'published', 'deprecated', name='template_state'), nullable=False),
    sa.Column('published_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('created_by_member_uuid', sa.UUID(as_uuid=False), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('deleted_at', sa.DateTime(timezone=True), nullable=True),
    sa.ForeignKeyConstraint(['created_by_member_uuid'], ['members.uuid'], ),
    sa.ForeignKeyConstraint(['default_retention_policy_uuid'], ['retention_policies.uuid'], ),
    sa.ForeignKeyConstraint(['workspace_uuid'], ['workspaces.uuid'], ),
    sa.PrimaryKeyConstraint('uuid')
    )
    op.create_index('idx_document_templates_workspace_category_subtype', 'document_templates', ['workspace_uuid', 'category', 'subtype'], unique=False)
    op.create_index('idx_document_templates_workspace_state', 'document_templates', ['workspace_uuid', 'state'], unique=False)
    op.create_table('document_instances',
    sa.Column('uuid', sa.UUID(as_uuid=False), nullable=False),
    sa.Column('workspace_uuid', sa.UUID(as_uuid=False), nullable=False),
    sa.Column('template_uuid', sa.UUID(as_uuid=False), nullable=False),
    sa.Column('template_version', sa.String(length=32), nullable=False),
    sa.Column('subject_member_uuid', sa.UUID(as_uuid=False), nullable=True),
    sa.Column('requester_member_uuid', sa.UUID(as_uuid=False), nullable=False),
    sa.Column('variables_snapshot', postgresql.JSONB(astext_type=sa.Text()), server_default=sa.text("'{}'::jsonb"), nullable=False),
    sa.Column('rendered_pdf_uri', sa.Text(), nullable=True),
    sa.Column('state', sa.Enum('draft', 'pending_review', 'approved', 'signed', 'issued', 'archived', 'archived_legal_only', 'void', name='document_instance_state'), nullable=False),
    sa.Column('review_workflow_uuid', sa.UUID(as_uuid=False), nullable=True),
    sa.Column('signature_request_uuid', sa.UUID(as_uuid=False), nullable=True),
    sa.Column('retention_policy_uuid', sa.UUID(as_uuid=False), nullable=False),
    sa.Column('retention_expires_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('issued_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('void_reason', sa.Text(), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['requester_member_uuid'], ['members.uuid'], ),
    sa.ForeignKeyConstraint(['retention_policy_uuid'], ['retention_policies.uuid'], ),
    sa.ForeignKeyConstraint(['subject_member_uuid'], ['members.uuid'], ),
    sa.ForeignKeyConstraint(['template_uuid'], ['document_templates.uuid'], ),
    sa.ForeignKeyConstraint(['workspace_uuid'], ['workspaces.uuid'], ),
    sa.PrimaryKeyConstraint('uuid')
    )
    op.create_index('idx_document_instances_retention_due', 'document_instances', ['retention_expires_at'], unique=False, postgresql_where=sa.text("state IN ('issued', 'archived')"))
    op.create_index('idx_document_instances_workspace_state', 'document_instances', ['workspace_uuid', 'state'], unique=False)
    op.create_index('idx_document_instances_workspace_subject_state', 'document_instances', ['workspace_uuid', 'subject_member_uuid', 'state'], unique=False)
    op.create_index('idx_document_instances_workspace_template_created', 'document_instances', ['workspace_uuid', 'template_uuid', 'created_at'], unique=False)
    op.create_table('review_workflows',
    sa.Column('uuid', sa.UUID(as_uuid=False), nullable=False),
    sa.Column('workspace_uuid', sa.UUID(as_uuid=False), nullable=False),
    sa.Column('instance_uuid', sa.UUID(as_uuid=False), nullable=False),
    sa.Column('steps_count', sa.Integer(), server_default=sa.text('0'), nullable=False),
    sa.Column('current_step_index', sa.Integer(), server_default=sa.text('0'), nullable=False),
    sa.Column('state', sa.Enum('pending', 'in_progress', 'approved', 'rejected', name='review_workflow_state'), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['instance_uuid'], ['document_instances.uuid'], ),
    sa.ForeignKeyConstraint(['workspace_uuid'], ['workspaces.uuid'], ),
    sa.PrimaryKeyConstraint('uuid')
    )
    op.create_index('idx_review_workflows_workspace_instance', 'review_workflows', ['workspace_uuid', 'instance_uuid'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index('idx_review_workflows_workspace_instance', table_name='review_workflows')
    op.drop_table('review_workflows')
    op.drop_index('idx_document_instances_workspace_template_created', table_name='document_instances')
    op.drop_index('idx_document_instances_workspace_subject_state', table_name='document_instances')
    op.drop_index('idx_document_instances_workspace_state', table_name='document_instances')
    op.drop_index('idx_document_instances_retention_due', table_name='document_instances', postgresql_where=sa.text("state IN ('issued', 'archived')"))
    op.drop_table('document_instances')
    op.drop_index('idx_document_templates_workspace_state', table_name='document_templates')
    op.drop_index('idx_document_templates_workspace_category_subtype', table_name='document_templates')
    op.drop_table('document_templates')
    op.drop_index('idx_retention_policies_workspace', table_name='retention_policies')
    op.drop_table('retention_policies')
    # ### end Alembic commands ###
