"""add remain table

Revision ID: c819c3d4451a
Revises: 8cd2001f7d4b
Create Date: 2026-05-10 21:09:39.796471

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'c819c3d4451a'
down_revision: Union[str, Sequence[str], None] = '8cd2001f7d4b'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('inbox_entries',
    sa.Column('uuid', sa.UUID(as_uuid=False), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('deleted_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('recipient_user_uuid', sa.UUID(as_uuid=False), nullable=False),
    sa.Column('sender_user_uuid', sa.UUID(as_uuid=False), nullable=True),
    sa.Column('title', sa.String(length=512), nullable=False),
    sa.Column('body', sa.Text(), nullable=True),
    sa.Column('read_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('category', sa.String(length=64), nullable=True),
    sa.ForeignKeyConstraint(['recipient_user_uuid'], ['users.uuid'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['sender_user_uuid'], ['users.uuid'], ondelete='SET NULL'),
    sa.PrimaryKeyConstraint('uuid')
    )
    op.create_table('board_cards',
    sa.Column('uuid', sa.UUID(as_uuid=False), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('deleted_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('team_uuid', sa.UUID(as_uuid=False), nullable=False),
    sa.Column('sprint_uuid', sa.UUID(as_uuid=False), nullable=False),
    sa.Column('title', sa.String(length=512), nullable=False),
    sa.Column('column_key', sa.String(length=64), nullable=False),
    sa.Column('description', sa.Text(), nullable=True),
    sa.Column('position', sa.Integer(), nullable=False),
    sa.Column('assignee_user_uuid', sa.UUID(as_uuid=False), nullable=True),
    sa.Column('reporter_user_uuid', sa.UUID(as_uuid=False), nullable=True),
    sa.ForeignKeyConstraint(['assignee_user_uuid'], ['users.uuid'], ondelete='SET NULL'),
    sa.ForeignKeyConstraint(['reporter_user_uuid'], ['users.uuid'], ondelete='SET NULL'),
    sa.ForeignKeyConstraint(['sprint_uuid'], ['sprints.uuid'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['team_uuid'], ['teams.uuid'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('uuid')
    )
    op.create_table('retro_boards',
    sa.Column('uuid', sa.UUID(as_uuid=False), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('deleted_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('sprint_uuid', sa.UUID(as_uuid=False), nullable=False),
    sa.Column('title', sa.String(length=256), nullable=True),
    sa.ForeignKeyConstraint(['sprint_uuid'], ['sprints.uuid'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('uuid')
    )
    op.create_table('week_milestones',
    sa.Column('uuid', sa.UUID(as_uuid=False), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('deleted_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('sprint_uuid', sa.UUID(as_uuid=False), nullable=False),
    sa.Column('owner_user_uuid', sa.UUID(as_uuid=False), nullable=False),
    sa.Column('title', sa.String(length=512), nullable=False),
    sa.Column('due_on', sa.DateTime(timezone=True), nullable=True),
    sa.Column('completed_at', sa.DateTime(timezone=True), nullable=True),
    sa.ForeignKeyConstraint(['owner_user_uuid'], ['users.uuid'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['sprint_uuid'], ['sprints.uuid'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('uuid')
    )
    op.create_table('retro_columns',
    sa.Column('uuid', sa.UUID(as_uuid=False), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('deleted_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('retro_board_uuid', sa.UUID(as_uuid=False), nullable=False),
    sa.Column('label', sa.String(length=128), nullable=False),
    sa.Column('sort_order', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['retro_board_uuid'], ['retro_boards.uuid'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('uuid')
    )
    op.create_table('retro_items',
    sa.Column('uuid', sa.UUID(as_uuid=False), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('deleted_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('retro_column_uuid', sa.UUID(as_uuid=False), nullable=False),
    sa.Column('body', sa.Text(), nullable=False),
    sa.Column('author_user_uuid', sa.UUID(as_uuid=False), nullable=True),
    sa.ForeignKeyConstraint(['author_user_uuid'], ['users.uuid'], ondelete='SET NULL'),
    sa.ForeignKeyConstraint(['retro_column_uuid'], ['retro_columns.uuid'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('uuid')
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('retro_items')
    op.drop_table('retro_columns')
    op.drop_table('week_milestones')
    op.drop_table('retro_boards')
    op.drop_table('board_cards')
    op.drop_table('inbox_entries')
    # ### end Alembic commands ###
