"""add outbox retry/dead-letter columns

Revision ID: da5d6952ff26
Revises: 96df5b3950ec
Create Date: 2026-06-27 00:19:30.659352

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'da5d6952ff26'
down_revision: Union[str, Sequence[str], None] = '96df5b3950ec'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('event_outbox', sa.Column('retry_count', sa.Integer(), server_default=sa.text('0'), nullable=False))
    op.add_column('event_outbox', sa.Column('next_attempt_at', sa.DateTime(timezone=True), nullable=True))
    op.add_column('event_outbox', sa.Column('dead_at', sa.DateTime(timezone=True), nullable=True))
    op.add_column('event_outbox', sa.Column('last_error', sa.Text(), nullable=True))
    op.create_index('idx_event_outbox_dead', 'event_outbox', ['dead_at'], unique=False, postgresql_where=sa.text('dead_at IS NOT NULL'))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index('idx_event_outbox_dead', table_name='event_outbox', postgresql_where=sa.text('dead_at IS NOT NULL'))
    op.drop_column('event_outbox', 'last_error')
    op.drop_column('event_outbox', 'dead_at')
    op.drop_column('event_outbox', 'next_attempt_at')
    op.drop_column('event_outbox', 'retry_count')
    # ### end Alembic commands ###
