"""add_user_profile

Revision ID: dd8ba2808f86
Revises: 8359081daf8f
Create Date: 2026-05-09 14:35:30.768237

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'dd8ba2808f86'
down_revision: Union[str, Sequence[str], None] = '8359081daf8f'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('user_profiles',
    sa.Column('user_uuid', sa.UUID(as_uuid=False), nullable=False),
    sa.Column('job_title', sa.String(length=100), nullable=True),
    sa.Column('timezone', sa.String(length=100), nullable=True),
    sa.Column('locale', sa.String(length=100), nullable=True),
    sa.Column('joined_at', sa.DateTime(timezone=True), nullable=True),
    sa.ForeignKeyConstraint(['user_uuid'], ['users.uuid'], ),
    sa.PrimaryKeyConstraint('user_uuid')
    )
    op.create_unique_constraint('uq_user_auth_id', 'users', ['auth_id'])
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint('uq_user_auth_id', 'users', type_='unique')
    op.drop_table('user_profiles')
    # ### end Alembic commands ###
