"""update dashboard aggregate view of team

Revision ID: e67a9eea35e9
Revises: 0495db78a34c
Create Date: 2026-05-28 13:22:07.725795

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'e67a9eea35e9'
down_revision: Union[str, Sequence[str], None] = '0495db78a34c'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('dashboard_configs',
    sa.Column('uuid', sa.UUID(as_uuid=False), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('deleted_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('team_uuid', sa.UUID(as_uuid=False), nullable=False),
    sa.Column('sprint_uuid', sa.UUID(as_uuid=False), nullable=False),
    sa.Column('course_label', sa.String(length=128), nullable=True),
    sa.Column('blocker_note', sa.Text(), nullable=True),
    sa.Column('next_deadline_label', sa.String(length=256), nullable=True),
    sa.ForeignKeyConstraint(['sprint_uuid'], ['sprints.uuid'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['team_uuid'], ['teams.uuid'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('uuid'),
    sa.UniqueConstraint('sprint_uuid', name='uq_dashboard_config_sprint')
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('dashboard_configs')
    # ### end Alembic commands ###
