"""add shared core: workspaces, members, audit_logs, etc

Revision ID: f03e4689ca8e
Revises: bce8e5e54b17
Create Date: 2026-06-26 22:24:16.688323

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = 'f03e4689ca8e'
down_revision: Union[str, Sequence[str], None] = 'bce8e5e54b17'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('roles',
    sa.Column('uuid', sa.UUID(as_uuid=False), nullable=False),
    sa.Column('workspace_uuid', sa.UUID(as_uuid=False), nullable=False),
    sa.Column('name', sa.Enum('owner', 'admin', 'member', 'guest', 'external', name='role_name'), nullable=False),
    sa.Column('scope_type', sa.Enum('workspace', 'resource', name='role_scope'), nullable=False),
    sa.Column('permissions', postgresql.JSONB(astext_type=sa.Text()), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('deleted_at', sa.DateTime(timezone=True), nullable=True),
    sa.ForeignKeyConstraint(['workspace_uuid'], ['workspaces.uuid'], ),
    sa.PrimaryKeyConstraint('uuid'),
    sa.UniqueConstraint('workspace_uuid', 'name', 'scope_type', name='uq_roles_workspace_name_scope')
    )
    op.create_index('idx_roles_workspace', 'roles', ['workspace_uuid'], unique=False)
    op.create_table('audit_logs',
    sa.Column('uuid', sa.UUID(as_uuid=False), nullable=False),
    sa.Column('workspace_uuid', sa.UUID(as_uuid=False), nullable=False),
    sa.Column('actor_member_uuid', sa.UUID(as_uuid=False), nullable=True),
    sa.Column('domain', sa.Enum('pm', 'comms', 'hr', 'documents', name='audit_domain'), nullable=False),
    sa.Column('action', sa.String(length=64), nullable=False),
    sa.Column('resource_type', sa.String(length=64), nullable=True),
    sa.Column('resource_uuid', sa.UUID(as_uuid=False), nullable=True),
    sa.Column('metadata', postgresql.JSONB(astext_type=sa.Text()), nullable=False),
    sa.Column('occurred_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('trace_id', sa.String(length=64), nullable=True),
    sa.ForeignKeyConstraint(['actor_member_uuid'], ['members.uuid'], ),
    sa.ForeignKeyConstraint(['workspace_uuid'], ['workspaces.uuid'], ),
    sa.PrimaryKeyConstraint('uuid')
    )
    op.create_index('idx_audit_logs_actor', 'audit_logs', ['actor_member_uuid'], unique=False)
    op.create_index('idx_audit_logs_workspace_domain_action', 'audit_logs', ['workspace_uuid', 'domain', 'action'], unique=False)
    op.create_index('idx_audit_logs_workspace_occurred', 'audit_logs', ['workspace_uuid', 'occurred_at'], unique=False)
    op.create_table('entity_links',
    sa.Column('uuid', sa.UUID(as_uuid=False), nullable=False),
    sa.Column('workspace_uuid', sa.UUID(as_uuid=False), nullable=False),
    sa.Column('source_type', sa.String(length=64), nullable=False),
    sa.Column('source_uuid', sa.UUID(as_uuid=False), nullable=False),
    sa.Column('target_type', sa.String(length=64), nullable=False),
    sa.Column('target_uuid', sa.UUID(as_uuid=False), nullable=False),
    sa.Column('link_kind', sa.Enum('references', 'derived_from', 'blocks', 'mentioned_in', name='entity_link_kind'), nullable=False),
    sa.Column('created_by_member_uuid', sa.UUID(as_uuid=False), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('deleted_at', sa.DateTime(timezone=True), nullable=True),
    sa.ForeignKeyConstraint(['created_by_member_uuid'], ['members.uuid'], ),
    sa.ForeignKeyConstraint(['workspace_uuid'], ['workspaces.uuid'], ),
    sa.PrimaryKeyConstraint('uuid')
    )
    op.create_index('idx_entity_links_source', 'entity_links', ['workspace_uuid', 'source_type', 'source_uuid'], unique=False)
    op.create_index('idx_entity_links_target_kind', 'entity_links', ['workspace_uuid', 'target_type', 'target_uuid', 'link_kind'], unique=False)
    op.create_table('role_assignments',
    sa.Column('uuid', sa.UUID(as_uuid=False), nullable=False),
    sa.Column('workspace_uuid', sa.UUID(as_uuid=False), nullable=False),
    sa.Column('member_uuid', sa.UUID(as_uuid=False), nullable=False),
    sa.Column('role_uuid', sa.UUID(as_uuid=False), nullable=False),
    sa.Column('resource_type', sa.String(length=64), nullable=True),
    sa.Column('resource_uuid', sa.UUID(as_uuid=False), nullable=True),
    sa.Column('expires_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('deleted_at', sa.DateTime(timezone=True), nullable=True),
    sa.ForeignKeyConstraint(['member_uuid'], ['members.uuid'], ),
    sa.ForeignKeyConstraint(['role_uuid'], ['roles.uuid'], ),
    sa.ForeignKeyConstraint(['workspace_uuid'], ['workspaces.uuid'], ),
    sa.PrimaryKeyConstraint('uuid')
    )
    op.create_index('idx_role_assignments_expires', 'role_assignments', ['expires_at'], unique=False)
    op.create_index('idx_role_assignments_member', 'role_assignments', ['member_uuid'], unique=False)
    op.create_index('idx_role_assignments_member_resource', 'role_assignments', ['member_uuid', 'resource_type', 'resource_uuid'], unique=False)
    op.create_index('idx_role_assignments_role', 'role_assignments', ['role_uuid'], unique=False)
    op.create_index('idx_role_assignments_workspace', 'role_assignments', ['workspace_uuid'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index('idx_role_assignments_workspace', table_name='role_assignments')
    op.drop_index('idx_role_assignments_role', table_name='role_assignments')
    op.drop_index('idx_role_assignments_member_resource', table_name='role_assignments')
    op.drop_index('idx_role_assignments_member', table_name='role_assignments')
    op.drop_index('idx_role_assignments_expires', table_name='role_assignments')
    op.drop_table('role_assignments')
    op.drop_index('idx_entity_links_target_kind', table_name='entity_links')
    op.drop_index('idx_entity_links_source', table_name='entity_links')
    op.drop_table('entity_links')
    op.drop_index('idx_audit_logs_workspace_occurred', table_name='audit_logs')
    op.drop_index('idx_audit_logs_workspace_domain_action', table_name='audit_logs')
    op.drop_index('idx_audit_logs_actor', table_name='audit_logs')
    op.drop_table('audit_logs')
    op.drop_index('idx_roles_workspace', table_name='roles')
    op.drop_table('roles')
    # ### end Alembic commands ###
