"""add pm proj, sprints

Revision ID: fdf5f2845854
Revises: f03e4689ca8e
Create Date: 2026-06-26 22:35:16.248392

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'fdf5f2845854'
down_revision: Union[str, Sequence[str], None] = 'f03e4689ca8e'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('projects',
    sa.Column('uuid', sa.UUID(as_uuid=False), nullable=False),
    sa.Column('workspace_uuid', sa.UUID(as_uuid=False), nullable=False),
    sa.Column('name', sa.String(length=100), nullable=False),
    sa.Column('slug', sa.String(length=64), nullable=False),
    sa.Column('lead_member_uuid', sa.UUID(as_uuid=False), nullable=True),
    sa.Column('visibility', sa.Enum('private', 'internal', 'public_in_workspace', name='project_visibility'), nullable=False),
    sa.Column('target_date', sa.DateTime(timezone=True), nullable=True),
    sa.Column('status', sa.Enum('planned', 'in_progress', 'paused', 'completed', 'cancelled', name='project_status'), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('deleted_at', sa.DateTime(timezone=True), nullable=True),
    sa.ForeignKeyConstraint(['lead_member_uuid'], ['members.uuid'], ),
    sa.ForeignKeyConstraint(['workspace_uuid'], ['workspaces.uuid'], ),
    sa.PrimaryKeyConstraint('uuid'),
    sa.UniqueConstraint('workspace_uuid', 'slug', name='uq_projects_workspace_slug')
    )
    op.create_index('idx_projects_lead', 'projects', ['lead_member_uuid'], unique=False)
    op.create_index('idx_projects_workspace_status', 'projects', ['workspace_uuid', 'status'], unique=False)
    op.create_table('pm_sprints',
    sa.Column('uuid', sa.UUID(as_uuid=False), nullable=False),
    sa.Column('workspace_uuid', sa.UUID(as_uuid=False), nullable=False),
    sa.Column('project_uuid', sa.UUID(as_uuid=False), nullable=True),
    sa.Column('name', sa.String(length=100), nullable=False),
    sa.Column('start_date', sa.DateTime(timezone=True), nullable=False),
    sa.Column('end_date', sa.DateTime(timezone=True), nullable=False),
    sa.Column('phase', sa.Enum('planned', 'active', 'completed', name='sprint_phase'), nullable=False),
    sa.Column('velocity', sa.Integer(), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('deleted_at', sa.DateTime(timezone=True), nullable=True),
    sa.ForeignKeyConstraint(['project_uuid'], ['projects.uuid'], ),
    sa.ForeignKeyConstraint(['workspace_uuid'], ['workspaces.uuid'], ),
    sa.PrimaryKeyConstraint('uuid')
    )
    op.create_index('idx_pm_sprints_project', 'pm_sprints', ['project_uuid'], unique=False)
    op.create_index('idx_pm_sprints_workspace_phase', 'pm_sprints', ['workspace_uuid', 'phase'], unique=False)
    op.create_table('issues',
    sa.Column('uuid', sa.UUID(as_uuid=False), nullable=False),
    sa.Column('workspace_uuid', sa.UUID(as_uuid=False), nullable=False),
    sa.Column('project_uuid', sa.UUID(as_uuid=False), nullable=True),
    sa.Column('sprint_uuid', sa.UUID(as_uuid=False), nullable=True),
    sa.Column('title', sa.String(length=200), nullable=False),
    sa.Column('description', sa.Text(), nullable=True),
    sa.Column('status', sa.Enum('backlog', 'todo', 'in_progress', 'blocked', 'done', 'cancelled', name='issue_status'), nullable=False),
    sa.Column('priority', sa.Enum('urgent', 'high', 'medium', 'low', name='issue_priority'), nullable=False),
    sa.Column('reporter_member_uuid', sa.UUID(as_uuid=False), nullable=False),
    sa.Column('assignee_member_uuid', sa.UUID(as_uuid=False), nullable=True),
    sa.Column('due_date', sa.DateTime(timezone=True), nullable=True),
    sa.Column('blocked_since', sa.DateTime(timezone=True), nullable=True),
    sa.Column('blocked_reason', sa.Text(), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('deleted_at', sa.DateTime(timezone=True), nullable=True),
    sa.ForeignKeyConstraint(['assignee_member_uuid'], ['members.uuid'], ),
    sa.ForeignKeyConstraint(['project_uuid'], ['projects.uuid'], ),
    sa.ForeignKeyConstraint(['reporter_member_uuid'], ['members.uuid'], ),
    sa.ForeignKeyConstraint(['sprint_uuid'], ['pm_sprints.uuid'], ),
    sa.ForeignKeyConstraint(['workspace_uuid'], ['workspaces.uuid'], ),
    sa.PrimaryKeyConstraint('uuid')
    )
    op.create_index('idx_issues_reporter', 'issues', ['reporter_member_uuid'], unique=False)
    op.create_index('idx_issues_workspace_assignee', 'issues', ['workspace_uuid', 'assignee_member_uuid'], unique=False)
    op.create_index('idx_issues_workspace_project', 'issues', ['workspace_uuid', 'project_uuid'], unique=False)
    op.create_index('idx_issues_workspace_sprint', 'issues', ['workspace_uuid', 'sprint_uuid'], unique=False)
    op.create_index('idx_issues_workspace_status', 'issues', ['workspace_uuid', 'status'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index('idx_issues_workspace_status', table_name='issues')
    op.drop_index('idx_issues_workspace_sprint', table_name='issues')
    op.drop_index('idx_issues_workspace_project', table_name='issues')
    op.drop_index('idx_issues_workspace_assignee', table_name='issues')
    op.drop_index('idx_issues_reporter', table_name='issues')
    op.drop_table('issues')
    op.drop_index('idx_pm_sprints_workspace_phase', table_name='pm_sprints')
    op.drop_index('idx_pm_sprints_project', table_name='pm_sprints')
    op.drop_table('pm_sprints')
    op.drop_index('idx_projects_workspace_status', table_name='projects')
    op.drop_index('idx_projects_lead', table_name='projects')
    op.drop_table('projects')
    # ### end Alembic commands ###
